### ISSUE TITLE
Image ID or name is hardcoded for Triton, Azure and GCP.

### ISSUE THREAD

**Issue by khangngu** [joyent/triton-kubernetes#23]
For AWS, the user must specify the image ID in the conf file.  But for Triton, Azure and GCP, the script uses hardcoded image ID (for ubuntu-16.04), and thus this may cause issue if:
a) The ubuntu-16.04 image has different ID's on different datacenters/regions/locations.
b) The image is not available on the datacenter/region/location used by the user.
c) The image is not accessible (due to lack of permission) by the user.

**Comment by fayazg** [comment]
Supported images are pulled using api: #35
