### ISSUE TITLE
Error with pre-create check when setting up new nodes on rancher using HA

### ISSUE THREAD

**Issue by pragmaticivan** [joyent/triton-kubernetes#30]
<img width="258" alt="screen shot 2018-01-08 at 10 09 12 am" src="https://user-images.githubusercontent.com/301291/34686829-b01bb0c6-f461-11e7-9909-c966d767fae9.png">
<img width="271" alt="screen shot 2018-01-08 at 10 09 17 am" src="https://user-images.githubusercontent.com/301291/34686830-b039a284-f461-11e7-9281-57eacf7c0e21.png">

**Comment by fayazg** [comment]
Can you give a little info on your environment?
Are you setting up nodes using rancher UI here? What parameters did you use?

**Comment by pragmaticivan** [comment]
```
## Name your kubernetes environment
name=triton-test
ha=true
## Comma separated names of triton networks to use
networks=public,My-Fabric-Network
## number of worker nodes for this Kubernetes environment
compute_count=5
## Triton packages to use for each of the dedicated node types
etcd_package=kvm_16g
orchestration_package=kvm_16g
compute_package=kvm_16g

## To use the default ubuntu-certified-16.04@20170619.1, comment out the _image_ options
triton_image_name=ubuntu-certified-16.04
triton_image_version=20170221

docker_engine_install_url=https://releases.rancher.com/install-docker/1.12.sh
```

I pretty much settled upa HA server with, even If I settled up compute_count=5, 

It just created 2 master computer + 1 mysql. Nothing else.

**Comment by fayazg** [comment]
```
networks=public,My-Fabric-Network
etcd_package=kvm_16g
orchestration_package=kvm_16g
compute_package=kvm_16g
```
Is this on public cloud or your own private Triton?

**Comment by pragmaticivan** [comment]
private Triton, but it has both networks.

**Comment by fayazg** [comment]
Didn't the cli (`./triton-kubernetes.sh -e triton_environment.conf`) throw any errors, or you using the UI with those parameters to create your environment?

**Comment by pragmaticivan** [comment]
Not really, it created the machines all right, but rancher is not able to create more nodes, maybe it's a problem with the driver it used for docker-machine with rancher

**Comment by fayazg** [comment]
It shouldn't use docker-machine if you used the CLI.
If you used the UI (it uses machine-driver), you have to enter `/root/.ssh/id_rsa` as the input for private key.

**Comment by pragmaticivan** [comment]
hey @fayazg this problem only happens if I try to add nodes using the UI before I perform the script with `-e`.

I will close that since it may not be relevant any way. 

I ended up having issues to understand what are people using for Storage with kubernetes when using triton.
