### ISSUE TITLE
Shell Scripts are targeting the JPC

### ISSUE THREAD

**Issue by Smithx10** [joyent/triton-kubernetes#37]
Currently,

The shell scripts to bootstrap rancher / k8s are based around package names and other things that may not exist in a private triton implementation.   

Perhaps it would make sense to have default variables for JPC that are easily overwritten in a .vars or in env vars.    I hard coded package names / network names  etc for my private cloud.

**Comment by fayazg** [comment]
Rewritten in Go, package/network/image names are not hardcoded anymore.
