### ISSUE TITLE
After installing kubernetes Rancher shows an unhealthy state

### ISSUE THREAD

**Issue by dekobon** [joyent/triton-kubernetes#41]
![screen shot 2018-01-23 at 2 11 35 pm](https://user-images.githubusercontent.com/490392/35303735-d0ae978a-0047-11e8-908f-1b47d9cd1aa3.png)

**Comment by dekobon** [comment]
Additionally, it alerts to tell you to use a supported version of docker. I'm not sure if it is related.

**Comment by fayazg** [comment]
This is the normal behavior. Once all the services are up on the correct nodes, health state will change to "Active".
And the supported version of docker message at the top is just a hint.

**Comment by dekobon** [comment]
I was actually more concerned about the "Unhealthy" row for Cattle. When doing a demo with a big red box that says "Unhealthy" the optics do not look good. Anything we can do to get the opening screen as clean as possible will be positive.

**Comment by fayazg** [comment]
removed the default cattle env in #66
