### ISSUE TITLE
jq should be added to the list of pre-requisites

### ISSUE THREAD

**Issue by watters** [joyent/triton-kubernetes#42]
If I run `./triton-kubernetes.sh` without `jq` installed, I get this:

```
$ ./triton-kubernetes.sh
error: jq is not in your PATH ...
       Make sure it is in your PATH and run this command again.
```

But `jq` is not listed as a pre-requisite in the README.md. It's mentioned in passing when it is explicitly used in a suggested AWS cli command, but that's it. It also doesn't tell me how to get it.

**Comment by fayazg** [comment]
New documentation includes `jq` as a pre-req: #70
