### ISSUE TITLE
There are only two networks to choose between in the installers

### ISSUE THREAD

**Issue by dekobon** [joyent/triton-kubernetes#43]
When running the installer for rancher or for kubernetes, you are given a network choice:
```
From below options:
Joyent-SDC-Public
Joyent-SDC-Private
Both
```

The `Joyent-SDC-Public` network is used for internet facing traffic and isn't appropriate for intra-node communication. It unneededly uses up IPs from our scare IP pool and puts network traffic on external NICs when it isn't necessary.  Additionally, many users may not even want to attach external NICs for security reasons.

The `Joyent-SDC-Private` network suffers from some serious flaws as reported in OPS-3341. Essentially, communication between different IP pools is impossible AND IPs from this network are accessible from other tenants within Joyent's infrastructure, so this isn't a viable _internal network_. Additionally, users will be charged for traffic over the external NIC.

**Comment by fayazg** [comment]
`triton-kubernetes` now pulls all network details by making API calls. What gets displayed as choices are what is available to the client.
