### ISSUE TITLE
Access control should be enabled at installation

### ISSUE THREAD

**Issue by clstokes** [joyent/triton-kubernetes#61]
Currently (as of https://github.com/joyent/triton-kubernetes/commit/45cccbf8bb6aed652e5cb4a23079990b06976ff5), the Rancher UI is open to anonymous users. [Local Authentication](http://rancher.com/docs/rancher/v1.6/en/configuration/access-control/#local-authentication) should be enabled by default and ideally with a random password created at installation to provide a relatively secure environment out-of-the-box.

**Comment by fayazg** [comment]
done in #93
