### ISSUE TITLE
Terraform module name mismatch in create-rancher.tf

### ISSUE THREAD

**Issue by joerawr** [joyent/triton-kubernetes#72]
For a Triton install, I was getting this error from Terraform:
```
Error: output 'masters': unknown module referenced: create_rancher

Error: output 'masters': reference to undefined module "create_rancher"
```
I think it's because in:
triton-kubernetes/terraform/create-rancher.tf

Line 7:  `module "create_rancher-example" {`

doesn't match the module called in lines 34-35:
```
output "masters" {
value = "${module.create_rancher.masters}"
```

When I changed line 7 to _create_rancher_ the Terraform section completed without errors.

Hope that helps.

**Comment by ShubhraKar** [comment]
This issue is related to the older bash version. Please try the new go-cli version and let us know if you still experience the same issue.

**Comment by joerawr** [comment]
Thanks for the response.  I'll try the go-cli version.
